#pragma once

#include <stm32f4xx_hal.h>

#ifdef __cplusplus
extern "C" {
#endif

#define BLTN_LED_PIN GPIO_PIN_13
#define BLTN_LED_GPIO_PORT GPIOC
#define BLTN_KEY_PIN GPIO_PIN_0
#define BLTN_KEY_GPIO_PORT GPIOA
#define BLTN_KEY_EXTI_IRQn EXTI0_IRQn

#define SDIO_CD_PIN GPIO_PIN_1
#define SDIO_CD_GPIO_PORT GPIOA
#define SDIO_CMD_PIN GPIO_PIN_6
#define SDIO_CMD_GPIO_PORT GPIOA
#define SDIO_CLK_PIN GPIO_PIN_15
#define SDIO_CLK_GPIO_PORT GPIOB
#define SDIO_D0_PIN GPIO_PIN_4
#define SDIO_D0_GPIO_PORT GPIOB
#define SDIO_D1_PIN GPIO_PIN_8
#define SDIO_D1_GPIO_PORT GPIOA
#define SDIO_D2_PIN GPIO_PIN_9
#define SDIO_D2_GPIO_PORT GPIOA
#define SDIO_D3_PIN GPIO_PIN_5
#define SDIO_D3_GPIO_PORT GPIOB

#define VGA_HSYNC_GPIO_PORT GPIOA
#define VGA_HSYNC_PIN GPIO_PIN_2
#define VGA_VSYNC_GPIO_PORT GPIOA
#define VGA_VSYNC_PIN GPIO_PIN_3
#define VGA_RGB_GPIO_PORT GPIOB
#define VGA_BLUE1_PIN GPIO_PIN_0
#define VGA_BLUE2_PIN GPIO_PIN_1
#define VGA_BLUE3_PIN GPIO_PIN_2
#define VGA_BLUE4_PIN GPIO_PIN_3
#define VGA_GREEN1_PIN GPIO_PIN_6
#define VGA_GREEN2_PIN GPIO_PIN_7
#define VGA_GREEN3_PIN GPIO_PIN_8
#define VGA_GREEN4_PIN GPIO_PIN_9
#define VGA_RED1_PIN GPIO_PIN_10
#define VGA_RED2_PIN GPIO_PIN_12
#define VGA_RED3_PIN GPIO_PIN_13
#define VGA_RED4_PIN GPIO_PIN_14

#define VGA_ALL_RED_PINS (VGA_RED1_PIN | VGA_RED2_PIN | VGA_RED3_PIN | VGA_RED4_PIN)
#define VGA_ALL_GREEN_PINS (VGA_GREEN1_PIN | VGA_GREEN2_PIN | VGA_GREEN3_PIN | VGA_GREEN4_PIN)
#define VGA_ALL_BLUE_PINS (VGA_BLUE1_PIN | VGA_BLUE2_PIN | VGA_BLUE3_PIN | VGA_BLUE4_PIN)
#define VGA_ALL_RGB_PINS (VGA_ALL_RED_PINS | VGA_ALL_GREEN_PINS | VGA_ALL_BLUE_PINS)
#define VGA_ALL_RGB_PINS_RESET (VGA_ALL_RGB_PINS << 16)

extern struct Notification gpio_button_notification;

void gpio_init(void);

#ifdef __cplusplus
}
#endif
