# <https://github.com/vpetrigo/arm-cmake-toolchains/blob/master/clang-arm-gcc-toolchain.cmake>

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_CROSSCOMPILING YES)
set(TOOLCHAIN_TARGET arm-none-eabi)

set(CMAKE_C_COMPILER   "clang"   CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "clang++" CACHE STRING "" FORCE)
set(CMAKE_ASM_COMPILER "clang"   CACHE STRING "" FORCE)

set(CMAKE_C_COMPILER_TARGET   "${TOOLCHAIN_TARGET}")
set(CMAKE_CXX_COMPILER_TARGET "${TOOLCHAIN_TARGET}")
set(CMAKE_ASM_COMPILER_TARGET "${TOOLCHAIN_TARGET}")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
