name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v3
      - uses: carlosperate/arm-none-eabi-gcc-action@v1
      - run: pip install elf-size-analyze
      - uses: actions/cache@v2
        with:
          path: target
          key: v1-${{github.workflow}}-${{runner.os}}-${{matrix.build_type}}-cmake
      - run: cmake -B 'target/${{matrix.build_type}}' -DCMAKE_BUILD_TYPE='${{matrix.build_type}}' -DDEPENDENCIES_DIR='target/_deps' -DUPLOAD_TOOL=OFF -DCMAKE_COLOR_DIAGNOSTICS=ON
      - run: cmake --build 'target/${{matrix.build_type}}' --config '${{matrix.build_type}}' --parallel "$(nproc)"
      - run: elf-size-analyze --rom --ram 'target/${{matrix.build_type}}/firmware.elf'
